"""
Module 01: ReAct Agent - Execution Engine.

This module implements the canonical ReAct (Reasoning + Acting) loop using Google Gemini.
It enforces the Think -> Act -> Observe -> Think cycle:
1. Thought: Agent reasons about current progress and chooses next step.
2. Action: Agent outputs a structured tool call.
3. Observation: Environment executes tool and feeds result back into the prompt context.
4. Loop repeats until 'Final Answer:' is formulated or max iterations reached.

Educational Concept:
- Shows how to implement ReAct from first principles without relying on monolithic frameworks.
- Transparently exposes prompt scaffolding, parsing regex, and observation injection.
"""

import re
import json
from typing import Dict, List, Optional, Tuple, Any
from shared.gemini_client import call_gemini, is_gemini_configured
from shared.console import AgentConsole
try:
    from .tools import TOOL_REGISTRY, TOOL_DESCRIPTIONS
except ImportError:
    from tools import TOOL_REGISTRY, TOOL_DESCRIPTIONS

REACT_SYSTEM_PROMPT = f"""You are a reasoning and tool-using AI assistant designed using the ReAct (Reasoning + Acting) framework.
Your task is to answer user queries by alternating between Thinking, Acting, and Observing.

{TOOL_DESCRIPTIONS}

Use the following STRICT format:

Question: the input question you must answer
Thought: reason about what to do next, what data you have, and what is missing
Action: the action to take, exactly matching one of the available tool names (e.g. search_flights)
Action Input: a JSON dictionary of arguments to pass to the tool (e.g. {{"origin": "COK", "destination": "BLR", "date": "2026-10-15"}})
Observation: the result of the action (provided by the environment)
... (this Thought/Action/Action Input/Observation cycle can repeat multiple times)
Thought: I now know the final answer
Final Answer: the comprehensive final answer to the original input question

IMPORTANT RULES:
1. Always output ONE Thought and ONE Action/Action Input at each step.
2. Wait for the Observation before writing the next Thought.
3. When you have enough information to answer the question thoroughly, output 'Thought: I now know the final answer' followed by 'Final Answer: <your response>'.
4. Do NOT hallucinate tool names. Only use the tools listed above.
"""


class ReActAgent:
    """
    Implements a self-contained ReAct agent loop backed by Google Gemini.
    """

    def __init__(self, max_iterations: int = 6):
        """
        Initializes the ReAct agent.

        Args:
            max_iterations (int): Safety ceiling on the number of action-observation
                                  cycles to prevent infinite loops.
        """
        self.max_iterations = max_iterations
        self.trajectory: List[str] = []

    def _parse_response(self, text: str) -> Tuple[Optional[str], Optional[str], Optional[Dict[str, Any]], Optional[str]]:
        """
        Extracts Thought, Action, Action Input, or Final Answer from LLM completion.

        In the original ReAct framework (Yao et al., 2022), the LLM generates free-form text
        following a specific grammar (Thought -> Action -> Action Input). Because this
        module demonstrates ReAct from first principles without depending on proprietary
        function-calling APIs, we use regular expressions to parse the model's text output
        into structured execution tokens.

        Args:
            text (str): Raw string output generated by Gemini for the current step.

        Returns:
            Tuple[Optional[str], Optional[str], Optional[Dict[str, Any]], Optional[str]]:
                - thought: The internal reasoning chain of the agent for this step.
                - action: The tool name selected by the model (None if final answer).
                - action_input: Dictionary of keyword arguments for the selected tool.
                - final_answer: The synthesized final response if the task is complete.
        """
        # -------------------------------------------------------------------------
        # 1. Extract "Thought:"
        # -------------------------------------------------------------------------
        # Regex breakdown:
        # - r"Thought:\s*"               : Matches the "Thought:" prefix and any trailing whitespace.
        # - (.*?)                        : Non-greedy capture of the agent's internal monologue/reasoning.
        # - (?=(Action:|Final Answer:|$)): Positive lookahead ensuring we stop capturing when
        #                                  the next section marker ("Action:" or "Final Answer:")
        #                                  or the end of the text is encountered.
        # - re.DOTALL                    : Allows '.' to match newline characters across multiple lines.
        # - re.IGNORECASE                : Handles potential case variations (e.g., 'thought:').
        thought_match = re.search(r"Thought:\s*(.*?)(?=(Action:|Final Answer:|$))", text, re.DOTALL | re.IGNORECASE)
        thought = thought_match.group(1).strip() if thought_match else None

        # -------------------------------------------------------------------------
        # 2. Extract "Final Answer:" (Termination condition)
        # -------------------------------------------------------------------------
        # If the model emits "Final Answer:", it has concluded its reasoning loop
        # and synthesized the final solution. In this case, no further tool actions
        # should be executed.
        # Regex breakdown:
        # - r"Final Answer:\s*(.*)" : Captures all remaining text after "Final Answer:".
        final_match = re.search(r"Final Answer:\s*(.*)", text, re.DOTALL | re.IGNORECASE)
        if final_match:
            final_answer = final_match.group(1).strip()
            # Return early with the thought and final answer; action and action_input are None.
            return thought, None, None, final_answer

        # -------------------------------------------------------------------------
        # 3. Extract "Action:" (Tool Selection)
        # -------------------------------------------------------------------------
        # When continuing the reasoning loop, the model specifies which tool to call.
        # Regex breakdown:
        # - r"Action:\s*([a-zA-Z0-9_]+)": Captures alphanumeric function names including underscores
        #                                 (e.g., 'search_flights', 'get_calendar_events').
        action_match = re.search(r"Action:\s*([a-zA-Z0-9_]+)", text, re.IGNORECASE)
        action = action_match.group(1).strip() if action_match else None

        # -------------------------------------------------------------------------
        # 4. Extract "Action Input:" (Tool Arguments)
        # -------------------------------------------------------------------------
        # The prompt instructs the model to provide tool arguments as valid JSON dictionary strings.
        # Regex breakdown:
        # - r"Action Input:\s*({.*?})" : Non-greedily captures a JSON object enclosed in curly braces.
        input_match = re.search(r"Action Input:\s*({.*?})", text, re.DOTALL | re.IGNORECASE)
        action_input = {}
        if input_match:
            try:
                # Parse JSON string into Python dict of keyword arguments
                action_input = json.loads(input_match.group(1).strip())
            except json.JSONDecodeError:
                # Defensive parsing: If the model emits malformed JSON, default to empty dict.
                # The execution step will subsequently trigger a descriptive tool error observation,
                # giving the LLM an opportunity to self-correct on the next iteration.
                action_input = {}

        return thought, action, action_input, None

    def run(self, user_query: str) -> str:
        """
        Executes the ReAct loop until resolution or max iterations.

        Args:
            user_query (str): The natural language query from the user.

        Returns:
            str: The final synthesized answer.
        """
        AgentConsole.banner("Module 01: ReAct Agent", "Pattern: Think -> Act -> Observe Loop")
        AgentConsole.user_query(user_query)

        # Initialize conversation scratchpad:
        # The scratchpad acts as the agent's short-term working memory, accumulating
        # the history of Questions, Thoughts, Actions, and Observations.
        prompt_history = f"Question: {user_query}\n"

        # Begin iterative ReAct loop (bounded by max_iterations to prevent infinite cycles)
        for step in range(1, self.max_iterations + 1):
            AgentConsole.step_header(step, "Reasoning & Action Selection")

            # -----------------------------------------------------------------
            # Step A: Prompt Generation & LLM Completion
            # -----------------------------------------------------------------
            # We append "\nThought:" to the end of prompt_history to prime the model
            # into generating its reasoning chain first (few-shot / prompt completion trick).
            response_text = call_gemini(
                prompt=f"{prompt_history}\nThought:",
                system_instruction=REACT_SYSTEM_PROMPT,
                temperature=0.1,
            )

            # Ensure 'Thought:' prefix is preserved if stripped by the model
            if not response_text.strip().startswith("Thought:"):
                response_text = f"Thought: {response_text}"

            # -----------------------------------------------------------------
            # Step B: Parse Structured Output
            # -----------------------------------------------------------------
            thought, action, action_input, final_answer = self._parse_response(response_text)

            # Log agent's internal reasoning
            if thought:
                AgentConsole.thought(thought, step=step)

            # Check for terminal state: Final Answer found
            if final_answer:
                AgentConsole.final_answer(final_answer)
                return final_answer

            # -----------------------------------------------------------------
            # Step C: Tool Execution & Observation Injection
            # -----------------------------------------------------------------
            if action:
                AgentConsole.action(action, action_input)

                # Execute action against registered Python functions
                if action in TOOL_REGISTRY:
                    try:
                        observation = TOOL_REGISTRY[action](**action_input)
                    except Exception as err:
                        # Catch runtime exceptions inside tool execution and format as observation
                        observation = json.dumps({"status": "error", "error": str(err)})
                else:
                    # Handle unknown/hallucinated tool names gracefully
                    observation = json.dumps({
                        "status": "error",
                        "message": f"Tool '{action}' is not in available tools registry."
                    })

                AgentConsole.observation(observation)

                # Append Thought, Action, Action Input, and Observation to the scratchpad
                # so the model has the complete trace in context for subsequent reasoning steps
                prompt_history += f"\nThought: {thought}\nAction: {action}\nAction Input: {json.dumps(action_input)}\nObservation: {observation}\n"
            else:
                # Model failed to choose an action or finalize; nudge it with an observation
                prompt_history += f"\nObservation: Please specify a valid Action and Action Input, or provide Final Answer.\n"

        # ---------------------------------------------------------------------
        # Fallback termination if safety ceiling is reached
        # ---------------------------------------------------------------------
        final_answer = "Reached maximum iterations without formulating a final answer."
        AgentConsole.final_answer(final_answer)
        return final_answer
