"""
Console Visualization Module for AI Agent Architectures.

Provides rich, colorful, structured terminal output for visualizing:
- Thought / Reasoning processes
- Action execution & tool invocations
- Observations & external API returns
- State machine transitions & graph nodes
- Critic / Evaluation grading reports
- Multi-agent messages & supervisor routing

Author: AI Agent Architectures Learning Repository
Target Models: Google Gemini Family
"""

import sys
from typing import Any, Dict, Optional

# Ensure UTF-8 output on Windows consoles to prevent cp1252 charmap encoding errors
if sys.platform == "win32":
    try:
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8")
        if hasattr(sys.stderr, "reconfigure"):
            sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich.markdown import Markdown

# Initialize shared Rich console
console = Console(safe_box=True)


class AgentConsole:
    """
    Structured logger and visualizer for AI agent trajectories and internal states.
    Designed to help learners visually trace step-by-step reasoning in real time.
    """

    @staticmethod
    def banner(title: str, subtitle: Optional[str] = None) -> None:
        """
        Renders a distinctive module header banner.

        Args:
            title: Module or architecture name (e.g., 'Module 01: ReAct Agent').
            subtitle: Optional descriptive tagline or architecture summary.
        """
        content = f"[bold cyan]{title}[/bold cyan]"
        if subtitle:
            content += f"\n[dim]{subtitle}[/dim]"
        console.print(
            Panel(
                content,
                border_style="bright_blue",
                padding=(1, 2),
                expand=True,
            )
        )

    @staticmethod
    def user_query(query: str) -> None:
        """Prints the incoming user prompt or task assignment."""
        console.print(
            Panel(
                f"[bold white]{query}[/bold white]",
                title="[bold green]User Query / Task[/bold green]",
                border_style="green",
                padding=(0, 2),
            )
        )

    @staticmethod
    def thought(thought_text: str, step: Optional[int] = None) -> None:
        """
        Prints an agent's internal reasoning (Thought step in ReAct/Planner).

        Args:
            thought_text: The reasoning generated by the model before acting.
            step: Optional 1-indexed step count in the loop.
        """
        title = f"[bold yellow]Thought (Step {step})[/bold yellow]" if step else "[bold yellow]Thought / Reasoning[/bold yellow]"
        console.print(
            Panel(
                f"[italic yellow]{thought_text.strip()}[/italic yellow]",
                title=title,
                border_style="yellow",
                padding=(0, 2),
            )
        )

    @staticmethod
    def action(tool_name: str, arguments: Any) -> None:
        """
        Prints an action / tool call selected by the agent.

        Args:
            tool_name: The target function or tool name being executed.
            arguments: Input arguments passed to the tool.
        """
        content = f"[bold magenta]Calling Tool:[/bold magenta] [bold white]{tool_name}[/bold white]\n"
        content += f"[magenta]Arguments:[/magenta] [dim]{arguments}[/dim]"
        console.print(
            Panel(
                content,
                title="[bold magenta]Action / Tool Call[/bold magenta]",
                border_style="magenta",
                padding=(0, 2),
            )
        )

    @staticmethod
    def observation(result: Any) -> None:
        """
        Prints the result returned by a tool or environment (Observation).

        Args:
            result: Raw or formatted output from the external tool execution.
        """
        content = f"[cyan]{str(result).strip()}[/cyan]"
        console.print(
            Panel(
                content,
                title="[bold cyan]Observation / Tool Result[/bold cyan]",
                border_style="cyan",
                padding=(0, 2),
            )
        )

    @staticmethod
    def critique(score: float, passed: bool, feedback: str, criteria: Optional[Dict[str, Any]] = None) -> None:
        """
        Prints the evaluation report from a Critic or Grader agent.

        Args:
            score: Quantitative rating (0.0 to 1.0 or 0 to 100).
            passed: Boolean indicating whether evaluation threshold was met.
            feedback: Constructive critique for revision.
            criteria: Optional breakdown of individual sub-scores.
        """
        status_text = "[bold green]PASSED[/bold green]" if passed else "[bold red]NEEDS REVISION[/bold red]"
        style = "green" if passed else "red"

        content = f"[bold]Status:[/bold] {status_text} (Score: {score:.1f}%)\n"
        content += f"[bold]Critique Feedback:[/bold]\n{feedback}\n"

        if criteria:
            content += "\n[bold]Criteria Breakdown:[/bold]\n"
            for key, val in criteria.items():
                content += f"  • {key}: {val}\n"

        console.print(
            Panel(
                content.strip(),
                title="[bold]Critic / Grader Evaluation[/bold]",
                border_style=style,
                padding=(0, 2),
            )
        )

    @staticmethod
    def final_answer(answer: str) -> None:
        """Prints the final user-facing response generated by the agent."""
        console.print(
            Panel(
                Markdown(answer),
                title="[bold green]Final Answer / Synthesis[/bold green]",
                border_style="bold green",
                padding=(1, 2),
            )
        )

    @staticmethod
    def step_header(step_num: int, name: str) -> None:
        """Prints a section divider for multi-step execution."""
        console.print(f"\n[bold blue]━━━ Step {step_num}: {name} ━━━[/bold blue]")
